version: 1.x-{build}
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: ''
  package_version: 1.0.2-build{build}
environment:
  WEBHOOK_URL:
    secure: p3nnkhnWtqFFH8UJ1eaKFfRjFPlOVhNtmLjd94R7+KSGMM5gIaSCCXQc0+d96gbwUsdAV1QA/fjzXIejubMKb0cUA0BbOULQuXQeKiTJxMDovuiLbp3lQKP5MAECLchRQsZTWPu4BTfol4QdF9iMhq5n+Opgpr0Ro7QA0ttM+so=
before_build:
- cmd: nuget restore "%APPVEYOR_BUILD_FOLDER%\ColorSeq.sln"
build:
  verbosity: minimal
after_build:
- cmd: 7z a devbuild.zip "%APPVEYOR_BUILD_FOLDER%\ColorSeq\bin\Debug\"
artifacts:
- path: devbuild.zip
  name: Development build of ColorSeq
- path: ColorSeq\bin\Debug\ColorSeq.*.nupkg
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: zV2DJaWY2ZIvXYrXofxz/Hy39XzVryc7Z13umuhiYBf6QJziJpeMFQfKkAnh+7T5
  symbol_server: https://www.nuget.org/api/v2/package
on_success:
- ps: >-
    Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1

    ./send.ps1 success $env:WEBHOOK_URL
on_failure:
- ps: >-
    Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1

    ./send.ps1 failure $env:WEBHOOK_URL